export const FR:any = {
    // Interface
    FGP:"Fonds de dotation Gérard Perrier",
    ACCUEIL:"Accueil",
    COMPTE:"Mon compte",
    COMPTE_INFOS:"Identifiez-vous ou créez un compte gérer vos favoris",
    RECHERCHE:"Rechercher",
    RECHERCHE_LIBRE:"Faire un recherche libre",
    RECHERCHE_LIBRE_DESCR:"(séparées par des virgules)",
    RECHERCHE_INFOS:"Vous pouvez effectuer une recherche libre sur les notices hébergées ou sélectionnez des critères plus spécifiques pour l'affiner.",
    RECHERCHE_COLLECTIONS:"Rechercher dans une collection (optionnel)",
    RECHERCHE_TOUT:"Tout",
    RECHERCHE_CHOIX:"Trouver une notice ou une collection ?",
    COLLECTIONS:"Collections hébergées",
    COLLECTION:"Collection",
    COLLEC_INFOS:"Les collections hébergées par le Fonds de Dotation Gérard Perrier, sont constituée d'orphelines ou de sujets de culture et de territoires.",
    NOTICE:"Notice",
    NOTICES:"Notices",
    FILTRE_NOTICES:"Filtrer les notices",
    FILTRE_SERIES:"Choisir une série de notices",
    CONTACT:"Nous contacter",
    AT:"Une plateforme gérée par le Fonds de dotation Gérard Perrier",
    DROITS:"Réalisation exlineo | Plateforme technique Nemateria",
    // Contenus du site
    filtre_series : "Filtrer les notices par séries",
    favoris_add : "Ajouter à vos favoris",
    favoris : "Favoris",
    favoris_collec : "Ajouter la collection à vos favoris",
    notices_view : "Voir les notices",
    notices : "Notices",
    notices_collec : "Afficher les notices de la collection",
    collections : "Collections",
    search : "Recherche",
    search_notices : "Rechercher dans ces notices",
    search_global : "Rechercher dans l'ensemble des collections",
    filter : "Filtrer",
    filter_notices : "Filtrer les notices",
    dublin_core : "Dublin Core"
}