export const FR:any = {
    // Interface
    FGP:"Fonds de dotation Gérard Perrier",
    ACCUEIL:"Accueil",
    COMPTE:"Mon compte",
    COMPTE_INFOS:"Identifiez-vous ou créez un compte gérer vos favoris",
    RECHERCHE:"Rechercher",
    RECHERCHE_LIBRE:"Faire un recherche libre",
    RECHERCHE_LIBRE_DESCR:"(séparées par des virgules)",
    RECHERCHE_INFOS:"Vous pouvez effectuer une recherche libre sur les notices hébergées ou sélectionnez des critères plus spécifiques pour l'affiner.",
    RECHERCHE_COLLECTIONS:"Rechercher dans une collection (optionnel)",
    RECHERCHE_TOUT:"Tout",
    RECHERCHE_CHOIX:"Trouver une notice ou une collection ?",
    COLLECTIONS:"Collections hébergées",
    COLLECTION:"Collection",
    COLLEC_INFOS:"Les collections hébergées par le Fonds de Dotation Gérard Perrier, sont constituée d'orphelines ou de sujets de culture et de territoires.",
    NOTICE:"Notice",
    NOTICES:"Notices",
    FILTRE_NOTICES:"Filtrer les notices",
    FILTRE_SERIES:"Choisir une série de notices",
    CONTACT:"Nous contacter",
    AT:"Une plateforme gérée par le Fonds de dotation Gérard Perrier",
    DROITS:"Réalisation exlineo | Plateforme technique Nemateria",
    // Metadonnées
    contributor : "Contributeur(s)",
    coverage : "Vignette",
    creator : "Céateur(s)",
    date : "Date",
    description : "Description",
    format : "Format",
    identifier : "Identifiant",
    language : "Langue",
    publisher : "Editeur",
    relation : "Relations(s)",
    rights : "Droits",
    source : "Source",
    subject : "Sujet(s)",
    title : "Titre",
    type : "Type",
    ImageLength : "Largeur",
    ImageWidth : "Hauteur",
    file : "Fichier",
    size : "Taille",
    url : "URL",
    access_conditions : "Conditions d'accès",
    attendees : "Participant(s)",
    certif_autority : "Autorité",
    certif_hash : "Hash",
    certif_politic : "Politique",
    certif_type : "Type",
    collection_funds : "Fonds",
    collection_infos : "Description",
    collection_location : "Localisation",
    collection_manager : "Gestionnaire",
    collection_name : "Collection",
    collection_rights_holders : "Détenteur des droits",
    contains_elements : "Contient",
    copyright : "Copyright",
    curator_file : "Conservateur",
    events_marks : "Marque",
    id : "Identifiant unique",
    informants : "Informateur(s)",
    informants_alias : "Alias des informateur(s)",
    informants_birthday : "Âge des informateurs",
    informants_skills : "Compétences des informateurs",
    latitude : "latitude",
    links_external_documents : "Liens vers des documents externes",
    links_internal_documents : "Liens vers des documents internes",
    longitude : "Longitude",
    numerisation_date : "Date de numérisation",
    original_creation_date : "Date de création originale",
    original_file : "Fichier d'origine",
    original_owner : "Détenteur de l'original",
    original_reference : "Référence de l'original",
    original_support_type : "Type de support de l'original",
    originals_curator : "Détenteur des originaux",
    productors : "Producteur",
    publisher_online : "Editeur en ligne",
    publisher_source_oeuvre : "Editeur de l'oeuvre d'origine",
    require_documents : "Document requis",
    rights_holders : "Détenteur des drois",
    sequences : "Séquences du média",
    sequences_durations : "Durées des séquences",
    sequences_keywords : "Mots clés des séquences",
    sequences_resumes : "Résumés des séquences",
    series : "Série(s)",
    series_order : "Ordre",
    series_parent : "Série parent",
    set_name : "Nom du Set",
    time_codes : "Code temporel",
    url_licence : "Lien vers la licence",
    where_digit : "Lieu de numérisation",
    where_preserv : "Lieu de préservation",
    where_subject : "Lieu dont il est question",
    who_scans : "Qui a scanné ?",
    // Contenus du site
    filtre_series : "Filtrer les notices par séries",
    favoris_add : "Ajouter à vos favoris",
    favoris : "Favoris",
    favoris_collec : "Ajouter la collection à vos favoris",
    notices_view : "Voir les notices",
    notices : "Notices",
    notices_collec : "Afficher les notices de la collection",
    collections : "Collections",
    search : "Recherche",
    search_notices : "Rechercher dans ces notices",
    search_global : "Rechercher dans l'ensemble des collections",
    filter : "Filtrer",
    filter_notices : "Filtrer les notices",
    dublin_core : "Dublin Core",
    dublin_metas : "Métadonnées normalisées Dublin Core",
    metas : "Métadonnées du document",
    media_infos : "Informations sur le document"
}